repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: check-added-large-files
        args: ['--maxkb=100000'] #  100MB
    -   id: check-case-conflict
    -   id: check-merge-conflict
    # -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: check-yaml
    -   id: requirements-txt-fixer
    -   id: double-quote-string-fixer
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: ["--ignore", "E501, W503"]
        additional_dependencies: [flake8-typing-imports==1.12.0]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
    -   id: autopep8
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.0.1
    hooks:
    -   id: reorder-python-imports
        args: [--py37-plus, --add-import, 'from __future__ import annotations']
        exclude: ^testing/resources/python3_hooks_repo/
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.1
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    -   id: mypy
